---
      - name: 'Install Apache, MySQL, PHP/Modules'
        yum:
         name:
          - httpd
          - php
          - mariadb-server
          - php-mysql
          - MySQL-python
         state: present

      - name: 'Restarting Services'
        service:
         name: "{{ item }}"
         state: restarted
         enabled: yes
        with_items:
          - httpd
          - mariadb

      - name: 'Create info.php'
        copy:
         content: '<?php phpinfo(); ?>'
         dest: /var/www/html/info.php

      - name: "Setup MySQL root password"
        ignore_errors: yes
        mysql_user:
          login_user: root
          login_password: ''
          name: root
          host_all: yes
          password: "{{mysql_root}}"
          
      - name: "Removing anonymous Users from Mysql DB"
        mysql_user:
          login_user: root
          login_password: "{{mysql_root}}"
          name: ''
          host_all: yes
          state: absent

